services:
  web:
    build:
      dockerfile: Dockerfile.jupyter
      context: ./docker/ 
    ports:
      - "8888:8888"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    working_dir: /home/notebook
    volumes:
    - workspace:/home/notebook
    - ./work:/home/notebook/work/
  db:
    build:
      dockerfile: Dockerfile.postgres
      context: ./docker/ 
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./database:/var/lib/postgresql/data
    ports:
    - 5432:5432
volumes:
  workspace: